version: "3.4"
services:
  db:
    image: rodrigodoe/mysql-spring-boot-api
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: spring-boot-api
    ports:
      - "3308:3306"
    networks:
      - spring-network
  spring-boot-api:
    image: rodrigodoe/spring-boot-api
    restart: always
    build: ./spring-boot-api
    working_dir: /spring-boot-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./spring-boot-api:/spring-boot-api
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge
